services:
  postgres:
    image: postgres:15
    restart: always
    volumes: # 왼쪽(현재 데이터) : 오른쪽(도커 이미지 데이터) => (동기화)
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres